[package]
name = "novi_projekat"
version = "0.1.0"
edition = "2024"
authors = ["Strale <strahinjastojanovic826@gmail.com>"]
description = "Mini amateur hobby OS kernel simulation with framebuffer UI written in Rust"
readme = "README.md"
repository = "https://github.com//Strale/novi_projekat"
license = "GPL-2.0-or-later"
keywords = ["os", "simulation", "ui", "hobby", "eframe", "quat os"] 

[dependencies]
eframe = "0.27"
